import airportImg from '../Servicepageimages/Airportarrival.png'
import cityImg from '../Servicepageimages/citytocitytravel.png'
import clientImg from '../Servicepageimages/Clientmeetingclient.png'
import corporateImg from '../Servicepageimages/Corporateevent.png'
import executiveTeamImg from '../Servicepageimages/executiveteamtransportation.png'
import meetingImg from '../Servicepageimages/Meeting.png'

const trustItems = [
  'Serving Southern California Since 1994',
  '1,900+ Combined Reviews',
  'Professional Chauffeurs & Executive Fleet',
  'Available 24/7/365',
]

const reviews = {
  ely: {
    text: "I have used Crown whenever I have to fly out of LAX. All the drivers are very professional, courteous, experienced drivers. Keep in touch with you enroute to pickups. I heartedly recommend them.",
    name: "Ely Licht",
    title: null,
    stars: 5,
  },
  natasha: {
    text: "Crown is fantastic. They are easy to communicate with, have excellent drivers, and understand that your schedule may need last minute adjustments. I have been using them for 20+ years and cannot say enough about their professionalism and high quality of service.",
    name: "Natasha Roit",
    title: null,
    stars: 5,
  },
  elena: {
    text: "Super easy to work with. Class act chauffeur and easy booking with great communication and beautiful, cushy Sprinter van for our corporate event. We will definitely use them again.",
    name: "Elena Mercer",
    title: "Dr. Martens – Americas | LA Office",
    stars: 5,
  },
  marykate: {
    text: "Crown Limousine was wonderful to work with. They were communicative, prompt, and flexible in a way that made planning a complicated trip extremely smooth. Our driver was kind and professional, and the entire team was helpful throughout the entire process from inquiry to end. Would recommend and will definitely use again!",
    name: "MaryKate Romagnoli",
    title: null,
    stars: 5,
  },
}

export const servicePages = [
  {
    slug: 'airport-transfers',
    image: airportImg,
    eyebrow: 'Airport Transportation',
    heroTitle: 'Luxury Airport Transportation Throughout Southern California',
    heroSubtitle: 'Crown Limousine LA has handled airport transportation for executives, business travelers, and corporate teams throughout Los Angeles since 1994. Flight tracked. Driver waiting. Everything already handled.',
    trustItems,
    problemHeadline: "Airport Transportation Should Not Be Something You're Worrying About Before A Flight",
    problemLead: 'You already have enough on your plate.',
    painPoints: [
      'A rideshare driver who cancels the morning of an early departure.',
      'No one tracking your flight when your landing is delayed.',
      'Walking through arrivals with no driver in sight.',
      'Scrambling for transportation after a long day of travel.',
      'A vehicle that doesn\'t match the standard you\'ve worked to maintain.',
      'Uncertainty about whether anyone is actually coming to pick you up.',
    ],
    problemConclusion: "Airport travel is already stressful. Transportation shouldn't add another layer of uncertainty.",
    problemConclusionStrong: 'Professional airport transportation means one less thing occupying your attention.',
    dreamTitle: 'Flight Tracked. Driver Waiting. Luggage Handled.',
    dreamPull: 'Everything is arranged before you even leave home.',
    dreamBody: [
      'Your chauffeur monitors your flight from departure to arrival. Delays, early landings, gate changes, handled automatically, without any coordination on your end.',
      'When you land, your driver is already there. You walk through arrivals and transportation is waiting.',
      'Luggage handled. Route planned. You\'re moving again before the stress of travel has a chance to set in.',
      'Whether you\'re departing at 4am or arriving after a cross-country red-eye, the experience is the same.',
    ],
    dreamClose: 'Every airport transfer, handled exactly right.',
    dreamCloseStrong: "So the only thing you're focused on is where you're going.",
    benefitsTitle: 'More Than Just A Ride To The Airport',
    benefits: [
      { title: 'Real-Time Flight Tracking', body: 'Your driver monitors your flight automatically. Delays, early arrivals, and gate changes are handled without any coordination required from you.' },
      { title: 'Punctual. Every Time.', body: "On-time pickup is not a bonus feature, it's the standard. Crown chauffeurs arrive early, whether it's a 4am departure or a late-night arrival." },
      { title: 'Start And End Every Trip Right', body: 'From the moment your driver arrives to the moment you clear security, or from landing to your front door, transportation is handled entirely.' },
    ],
    servicesTitle: 'Airport Transportation Services',
    services: [
      { title: 'LAX Transportation', body: 'Professional, punctual service to and from Los Angeles International Airport, departures and arrivals.' },
      { title: 'Burbank Airport Transportation', body: 'Reliable executive transportation to and from Hollywood Burbank Airport.' },
      { title: 'Long Beach Airport Transportation', body: 'Punctual service to and from Long Beach Airport for executives and business travelers.' },
      { title: 'Private Aviation Transportation', body: 'Professional transportation to and from private terminals and FBOs throughout Southern California.' },
      { title: 'Executive Airport Transfers', body: 'Premium chauffeured airport transportation meeting the standards of executives and business professionals.' },
      { title: 'Group Airport Transportation', body: 'Coordinated multi-vehicle airport transportation for teams, visiting delegations, and corporate groups.' },
    ],
    fleetVehicles: ['Cadillac Escalade', 'Cadillac XT6', 'Cadillac XTS', 'Tesla Model S', 'Mercedes Sprinter'],
    reviews: [reviews.ely, reviews.natasha, reviews.elena, reviews.marykate],
  },
  {
    slug: 'business-meetings',
    image: meetingImg,
    eyebrow: 'Business Meeting Transportation',
    heroTitle: 'Arrive Prepared. Arrive Professional.',
    heroSubtitle: 'Crown Limousine LA handles transportation for executives, attorneys, consultants, and business professionals throughout Los Angeles and Southern California. Your focus stays on the meeting, not the drive.',
    trustItems,
    problemHeadline: 'Transportation Becomes One More Thing Demanding Attention Before An Important Meeting',
    problemLead: 'You have enough to prepare for.',
    painPoints: [
      'Traffic making you late and arriving already stressed.',
      'Parking delays eating into your preparation time.',
      'Rideshare uncertainty when professionalism matters most.',
      'Arriving rushed instead of composed and ready.',
      'Your focus pulled to logistics rather than the meeting itself.',
      'First impressions being shaped before you say a word.',
    ],
    problemConclusion: 'The meeting starts before you walk through the door. How you arrive matters.',
    problemConclusionStrong: 'Professional transportation means arriving focused, composed, and ready.',
    dreamTitle: 'You Prepare For The Meeting. Transportation Is Already Handled.',
    dreamPull: 'Your drive becomes productive time.',
    dreamBody: [
      'While your chauffeur handles the route, traffic, and timing, you use the drive to review notes, prepare talking points, or take a call.',
      'You arrive composed. Not rushed. Not distracted by parking or navigation.',
      'No rideshare uncertainty. No unfamiliar driver. No last-minute scrambling.',
      'Every detail of your transportation is handled so your full attention belongs to the meeting ahead.',
    ],
    dreamClose: 'You walk in prepared. Professional. Exactly as you should.',
    dreamCloseStrong: 'Because transportation should never be a reason for a bad meeting.',
    benefitsTitle: 'Transportation That Works As Hard As You Do',
    benefits: [
      { title: 'Use The Drive Productively', body: 'Review files, take calls, prepare talking points. Your commute becomes working time when someone else is handling the driving.' },
      { title: 'Arrive Focused', body: 'No parking stress. No navigation. No rideshare delays. You step out of the vehicle exactly as prepared as you need to be.' },
      { title: 'Professional From Start To Finish', body: 'The vehicle, the chauffeur, the timing, every detail reflects the same standard you hold in your work.' },
    ],
    servicesTitle: 'Business Meeting Transportation Services',
    services: [
      { title: 'Executive Transportation', body: 'Professional, punctual chauffeured transportation for executives and senior professionals.' },
      { title: 'Business Meeting Transportation', body: 'Door-to-door service ensuring you arrive on time, prepared, and professionally represented.' },
      { title: 'Client Meeting Transportation', body: 'Arrive at client meetings composed and ready, not rushed from navigating traffic and parking.' },
      { title: 'City-to-City Executive Travel', body: 'Comfortable, productive transportation between Los Angeles and neighboring cities throughout Southern California.' },
      { title: 'Airport-to-Meeting Transportation', body: 'Direct, seamless service from airport arrival straight to your next meeting without the usual friction in between.' },
    ],
    fleetVehicles: ['Cadillac Escalade', 'Cadillac XT6', 'Cadillac XTS', 'Tesla Model S', 'Mercedes Sprinter'],
    reviews: [reviews.natasha, reviews.marykate, reviews.ely, reviews.elena],
  },
  {
    slug: 'client-transportation',
    image: clientImg,
    eyebrow: 'Client Transportation',
    heroTitle: 'Professional Transportation For Your Most Important Clients',
    heroSubtitle: 'The client experience begins before the meeting. Crown Limousine LA ensures your clients are greeted professionally, transported comfortably, and arrive with exactly the impression you want them to have.',
    trustItems,
    problemHeadline: 'Clients Notice Details. Transportation Is One Of Them.',
    problemLead: 'The impression your company makes starts long before the meeting begins.',
    painPoints: [
      'A client arriving stressed from an unreliable pickup.',
      "Transportation that doesn't match the standard of your brand.",
      'A client left waiting at an airport or hotel.',
      'The first interaction with your company leaving the wrong impression.',
      'Outsourcing something important to an unpredictable service.',
      'A small detail creating a lasting negative perception.',
    ],
    problemConclusion: 'How you handle client transportation tells clients how you handle everything.',
    problemConclusionStrong: "Professional client transportation isn't a luxury. It's a reflection of your standards.",
    dreamTitle: 'Your Client Is Greeted Professionally. Transported Comfortably. Impressed Before You Say A Word.',
    dreamPull: 'The meeting starts before the meeting starts.',
    dreamBody: [
      'Your client is greeted at the airport by a uniformed professional chauffeur. Name sign in hand. Everything organized and ready.',
      'The vehicle is executive standard. The experience is seamless. No uncertainty, no delays, no uncomfortable moments.',
      'Your client arrives at the meeting relaxed, comfortable, and with a clear sense of how you operate.',
      "First impressions don't just happen when you shake hands. They happen the moment your client lands.",
    ],
    dreamClose: 'Client transportation done right.',
    dreamCloseStrong: 'Because how you treat clients before the meeting says everything about how you treat them during it.',
    benefitsTitle: 'Client Transportation That Reflects Your Standards',
    benefits: [
      { title: 'The Right First Impression', body: 'A professional chauffeur, a premium vehicle, and flawless execution tell your client everything about how you do business before you say a word.' },
      { title: 'Completely Handled', body: 'From pickup coordination to arrival timing, every detail is managed so you can focus on the meeting rather than logistics.' },
      { title: 'Reflects Your Brand', body: "Your client transportation is a visible expression of your standards. Crown ensures it matches the level of professionalism you've built your reputation on." },
    ],
    servicesTitle: 'Client Transportation Services',
    services: [
      { title: 'VIP Client Transportation', body: 'Premium chauffeured service for your highest-value clients and most important relationships.' },
      { title: 'Executive Client Transfers', body: 'Professional door-to-door transportation for clients throughout Los Angeles and Southern California.' },
      { title: 'Airport Client Pickups', body: 'Professional meet-and-greet service ensuring your clients are welcomed and transported seamlessly from arrival.' },
      { title: 'Meeting Transportation', body: 'Reliable, professional transportation to and from meetings, ensuring your client arrives on time and composed.' },
      { title: 'Corporate Hospitality Transportation', body: 'Coordinated transportation for client events, dinners, site visits, and corporate hospitality programs.' },
    ],
    fleetVehicles: ['Cadillac Escalade', 'Cadillac XT6', 'Cadillac XTS', 'Tesla Model S', 'Mercedes Sprinter'],
    reviews: [reviews.marykate, reviews.elena, reviews.natasha, reviews.ely],
  },
  {
    slug: 'city-to-city',
    image: cityImg,
    eyebrow: 'City-To-City Executive Travel',
    heroTitle: 'Turn Travel Time Into Productive Time',
    heroSubtitle: 'Professional chauffeured transportation between Los Angeles, Orange County, San Diego, Santa Barbara, and throughout Southern California. Your chauffeur handles the drive while you stay focused.',
    trustItems,
    problemHeadline: 'Southern California Traffic Turns Simple Travel Into A Draining Experience',
    problemLead: 'Hours spent behind the wheel are hours not spent on higher-value work.',
    painPoints: [
      'Hours of driving that leave you exhausted before the meeting even begins.',
      'Lost preparation time on drives between cities.',
      'Traffic unpredictability making scheduling difficult.',
      'Arriving drained from a long, stressful drive.',
      'No way to work, prepare, or decompress during the journey.',
      'City-to-city travel becoming a recurring productivity drain.',
    ],
    problemConclusion: 'Every hour spent driving is an hour that could be spent preparing, thinking, or recovering.',
    problemConclusionStrong: 'Executive travel should be a productive part of your day, not a cost to it.',
    dreamTitle: 'Your Chauffeur Handles The Drive. You Handle What Matters.',
    dreamPull: 'Southern California travel without the drain.',
    dreamBody: [
      'While your chauffeur manages the route, traffic, and timing between cities, you use the time however it serves you best.',
      'Review materials. Take calls. Prepare for the next meeting. Or simply rest and arrive refreshed.',
      "No white-knuckle driving on the 405. No parking stress in an unfamiliar city. No arriving exhausted.",
      'City-to-city travel becomes a productive block of time in your schedule rather than a blank space of lost hours.',
    ],
    dreamClose: 'Los Angeles to San Diego. Los Angeles to Santa Barbara. Wherever the work takes you.',
    dreamCloseStrong: 'Professional transportation throughout Southern California, handled entirely.',
    benefitsTitle: 'Make Every Journey Count',
    benefits: [
      { title: 'Productive Travel Time', body: 'Your commute between cities becomes working time. Calls, preparation, review, the drive is yours to use however you need.' },
      { title: 'Arrive Ready', body: 'Skip the fatigue of long-distance driving and arrive at your destination composed, prepared, and ready to perform.' },
      { title: 'Comfortable For Long Journeys', body: 'Premium executive vehicles designed for extended comfort on longer routes throughout Southern California.' },
    ],
    servicesTitle: 'City-To-City Transportation Services',
    services: [
      { title: 'Los Angeles to Orange County', body: 'Professional executive transportation between Los Angeles and Orange County, Newport Beach, Irvine, and surrounding areas.' },
      { title: 'Los Angeles to San Diego', body: 'Comfortable, productive transportation between Los Angeles and San Diego for executives and business professionals.' },
      { title: 'Los Angeles to Santa Barbara', body: 'Scenic, relaxed executive transportation between Los Angeles and Santa Barbara.' },
      { title: 'Los Angeles to Inland Empire', body: 'Professional transportation between Los Angeles and the Inland Empire region.' },
      { title: 'Long-Distance Executive Transportation', body: 'Extended executive transportation throughout Southern California for any distance or destination.' },
    ],
    fleetVehicles: ['Cadillac Escalade', 'Cadillac XT6', 'Cadillac XTS', 'Tesla Model S', 'Mercedes Sprinter'],
    reviews: [reviews.natasha, reviews.marykate, reviews.ely, reviews.elena],
  },
  {
    slug: 'corporate-events',
    image: corporateImg,
    eyebrow: 'Corporate Event Transportation',
    heroTitle: 'Corporate Transportation Without The Logistical Headaches',
    heroSubtitle: 'Crown Limousine LA coordinates professional transportation for corporate conferences, executive meetings, conventions, and events throughout Los Angeles and Southern California. Every attendee arrives on time.',
    trustItems,
    problemHeadline: 'Coordinating An Event Already Has Enough Moving Parts',
    problemLead: 'Transportation should not be a added worry.',
    painPoints: [
      'Attendees arriving at different times in different vehicles with no coordination.',
      'Transportation delays disrupting a carefully scheduled event.',
      'Last-minute cancellations creating gaps in an already tight timeline.',
      'Managing transportation logistics pulling focus away from running the event.',
      'VIP speakers or executives arriving via unreliable services.',
      'Transportation becoming a source of complaints rather than a seamless experience.',
    ],
    problemConclusion: 'Corporate events already demand enough coordination. Transportation should be one thing you can simply check off the list.',
    problemConclusionStrong: 'Fully managed. Fully reliable. Everything handled.',
    dreamTitle: 'Every Passenger Arrives Where They Need To Be, When They Need To Be There.',
    dreamPull: 'No oversight required on your end.',
    dreamBody: [
      'Multi-vehicle coordination handled from a single point of contact. Schedules, routes, and timing all managed together.',
      'VIP speakers, executive attendees, keynote guests, each one transported professionally, on schedule, without exception.',
      "Your event runs as planned. Not because you're monitoring transportation, but because it's already been handled.",
      'From the opening session to the final transfer, Crown manages every vehicle, every pickup, every timeline.',
    ],
    dreamClose: 'Corporate event transportation managed entirely.',
    dreamCloseStrong: 'So you can focus on running the event, not managing the cars.',
    benefitsTitle: "Corporate Transportation That Doesn't Create More Work",
    benefits: [
      { title: 'Single Point Of Contact', body: 'One contact manages all vehicles, schedules, and coordination for your entire event. No fragmented logistics. No multiple services to manage.' },
      { title: 'Multi-Vehicle Coordination', body: 'Whether you need two vehicles or twenty, Crown coordinates them as a unified fleet with synchronized scheduling throughout your event.' },
      { title: 'VIP-Level Service For Every Passenger', body: 'Executive speakers, leadership teams, and VIP guests all receive the same professional, premium transportation experience.' },
    ],
    servicesTitle: 'Corporate Event Transportation Services',
    services: [
      { title: 'Corporate Conferences', body: 'Professional transportation for multi-day conferences, arrivals, departures, shuttles, and VIP coordination.' },
      { title: 'Executive Meetings', body: 'Reliable transportation for executive gatherings, board meetings, and leadership events.' },
      { title: 'Convention Transportation', body: 'Coordinated transportation for convention attendance at LACC, Anaheim, and major SoCal venues.' },
      { title: 'Multi-Vehicle Coordination', body: 'Synchronized fleet management for large groups requiring multiple vehicles and coordinated scheduling.' },
      { title: 'VIP Transportation', body: 'Premium, personalized service for keynote speakers, executives, and high-priority event attendees.' },
      { title: 'Group Transportation', body: 'Professional group transportation for teams, delegations, and large attendee groups throughout Los Angeles.' },
    ],
    fleetVehicles: ['Cadillac Escalade', 'Cadillac XT6', 'Cadillac XTS', 'Tesla Model S', 'Mercedes Sprinter'],
    reviews: [reviews.elena, reviews.marykate, reviews.natasha, reviews.ely],
  },
  {
    slug: 'executive-team',
    image: executiveTeamImg,
    eyebrow: 'Executive Team Transportation',
    heroTitle: 'Keep Your Team Moving Together',
    heroSubtitle: 'Crown Limousine LA coordinates transportation for leadership teams, visiting executives, and corporate groups throughout Southern California. Coordinated. On time. Professionally handled.',
    trustItems,
    problemHeadline: 'Managing Transportation For Multiple Executives Creates Unnecessary Complexity',
    problemLead: 'When transportation is fragmented, so is the team.',
    painPoints: [
      'Executives arriving separately with no coordination.',
      'Different team members using different services with inconsistent results.',
      "Scheduling gaps when individual schedules don't align.",
      'Time spent coordinating rides for individuals instead of focusing on the work.',
      'Visiting executives receiving a fragmented, unpolished experience.',
      'A lack of cohesion in how your team travels reflecting poorly on the organization.',
    ],
    problemConclusion: "Team transportation that's fragmented creates friction at every step.",
    problemConclusionStrong: 'Coordinated executive team transportation eliminates the complexity.',
    dreamTitle: 'The Entire Team Arrives Coordinated, Prepared, And On Schedule.',
    dreamPull: 'One plan. One point of contact. Every executive accounted for.',
    dreamBody: [
      'A single transportation plan covers the entire team. Pickups, timelines, and routes are coordinated so every executive arrives exactly when and where they need to.',
      'Visiting executives receive the same professional experience as your internal leadership, without anyone having to manage it individually.',
      'No one is left wondering about their transportation. No last-minute scrambling. No coordination calls.',
      'The team moves together, professionally, without the organizational overhead that fragmented transportation creates.',
    ],
    dreamClose: 'Executive team transportation, fully coordinated.',
    dreamCloseStrong: 'So leadership can focus on leading, not logistics.',
    benefitsTitle: 'Transportation That Keeps The Team Together',
    benefits: [
      { title: 'Fully Coordinated', body: 'Every pickup, every schedule, every route coordinated through one point of contact. The team moves as a unit, not as individuals.' },
      { title: 'Consistent For Every Executive', body: 'Internal leadership and visiting executives receive the same professional, premium experience without exception or inconsistency.' },
      { title: 'Eliminates The Overhead', body: "No one on your team spends time coordinating rides. No fragmented logistics. Transportation is one less organizational burden." },
    ],
    servicesTitle: 'Executive Team Transportation Services',
    services: [
      { title: 'Executive Team Travel', body: 'Coordinated transportation for leadership teams traveling to meetings, events, and corporate functions.' },
      { title: 'Leadership Meetings', body: 'Professional transportation ensuring your leadership team arrives together, on time, and prepared.' },
      { title: 'Visiting Executive Transportation', body: 'A premium experience for visiting executives, board members, and VIP guests from arrival to departure.' },
      { title: 'Group Airport Transfers', body: 'Coordinated multi-vehicle airport pickup and drop-off for teams traveling together.' },
      { title: 'Corporate Retreat Transportation', body: 'Full transportation coordination for corporate retreats, off-sites, and multi-day team travel.' },
    ],
    fleetVehicles: ['Cadillac Escalade', 'Cadillac XT6', 'Cadillac XTS', 'Tesla Model S', 'Mercedes Sprinter'],
    reviews: [reviews.marykate, reviews.elena, reviews.natasha, reviews.ely],
  },
]
